# Generated by Django 2.2.4 on 2019-08-23 08:34

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('gnum', models.IntegerField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=5)),
                ('sage', models.IntegerField()),
                ('scard', models.CharField(max_length=18)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('lasttime', models.DateTimeField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('gradeid', models.ForeignKey(on_delete=models.SET('班级删除'), to='myApp.Grades')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['id'],
            },
            managers=[
                ('stuobj', django.db.models.manager.Manager()),
            ],
        ),
    ]
